Lab08 kelsie
PdxCodeGuild/HB3 pull request #128
Opened 2022-12-07 03:02 UTC by kelsietwiss

Finished v1 and v2 of the ATM lab

2022-12-08 04:03 UTC, justin-young5 submitted a review, later dismissed
Depositing money doesn't accumulate into balance.  If I deposit 500, check balance is 500, then if I deposit 200, check balance is 200, when it should return 700.  Check your deposit function.

2022-12-14 00:24 UTC, violette-git requested changes

2022-12-14 00:24 UTC, violette-git commented on code/kelsie/lab08/lab08_kelsie.py
> +        self.balance = self.balance =+ amount
You have one symbol too many in your deposit function here on line 10. Test your program by running it, depositing some amount, then calculate interest. and then ask for the balance again. You will see a response that only returns the interest. 

Only one character needs to be removed, If you find yourself changing more than that then let me know.

2022-12-14 03:46 UTC, kelsietwiss commented
I made several commits in the process of fixing an issue I was having with git, but I am pretty sure that the final versions are submitted. Let me know if there is any issue.

2022-12-14 05:04 UTC, violette-git approved these changes

2022-12-14 05:04 UTC, merged